name: chat_babakcode
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-151.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  emoji_picker_flutter: ^1.1.2
  file_picker: ^5.2.2
  record: ^4.4.3
  intl: ^0.17.0
  firebase_messaging: ^14.1.0
  firebase_core: ^2.2.0
  syncfusion_flutter_pdf: ^20.1.58-beta
#  path_provider: any
  open_file: any
  lottie: ^1.3.0
  phlox_animations: ^2.1.1
  dio: ^4.0.6
  socket_io_client: ^2.0.0
  shamsi_date: ^1.0.1
  just_audio: ^0.9.28
  flutter_local_notifications: ^10.0.0-dev.22
  cached_network_image: ^3.2.0
  detectable_text_field: ^2.0.4
  crypto: ^3.0.2
  encrypt: ^5.0.1
  scrollable_positioned_list: ^0.3.5
  convert: ^3.1.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  custom_pop_up_menu: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.3.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
